sudo: false
language: java
jdk:
  - oraclejdk8
install:
  - wget --quiet --output-document=/tmp/ceylon.zip $CEYLON
  - unzip /tmp/ceylon.zip
  - export PATH=$PATH:$PWD/ceylon-1.3.2/bin/
  - export CEYLON_HOME=$PWD/ceylon-1.3.2
script:
  - ./gradlew install build
env:
  global:
    - CEYLON="http://ceylon-lang.org/download/dist/1_3_2"

